export const spacing = {
  xxs: 4,
  xs: 6,
  sm: 10,
  md: 14,
  lg: 18,
  xl: 24,
  xxl: 32,
  screenPadding: 16,
  cardPadding: 16,
  gridGap: 12,
  sectionGap: 22,
  elementGap: 12,
  inputHeight: 50,
  inputRadius: 12,
  buttonHeight: 50,
  buttonRadius: 13,
  chipRadius: 18,
  headerHeight: 56,
  tabBarHeight: 64,
  cardRadius: 14,
  mainCardRadius: 18,
} as const;

export type Spacing = typeof spacing;
